### ISSUE TITLE
"aliasID" is null

### ISSUE THREAD

**Issue by peri103** [code-philia/microbat#24]
Cannot invoke "String.equals(Object)" because "aliasID" is null.
Case: Csv 5

**Comment by HongshuW** [comment]
**Problem with Csv 5**
At step 141: expand StringWriter `out`, perform alias inference on `out.buf.value`.
An `NullPointerException` will be thrown at step 135 during alias inferencing, since this step includes a String (doesn't have alias ID). The exception is thrown by line 280 of `addVarSkeletonToVariablesOnTrace` method, where `aliasID` is null.

**Fix**
Skip variables without proper aliasID.

**Outcome**
After alias and definition inferencing, the data dominator at step 135 is found.
<img width="450" alt="Screenshot 2024-08-07 at 4 40 06 PM" src="https://github.com/user-attachments/assets/52c22194-e392-44a9-9e2f-5b3b15daaa48">
